#!/bin/bash

# ./script <old image sha>

IMAGEOLD=$1
TMP=/tmp

dirold=$TMP/compare-old
dirnew=$TMP/compare-new
mkdir -p $dirold $dirnew

#echo "Getting old image $IMAGEOLD"
git -C $dirold init &>/dev/null
git -C $dirold remote add origin https://github.com/packethost/packet-images.git &>/dev/null
git -C $dirold fetch origin &>/dev/null
git -C $dirold checkout "$IMAGEOLD" &>/dev/null

echo "======================================================================"
echo "Image size:"
echo "======================================================================"
echo "OLD image: $(du -sh $dirold/image.tar.gz | awk {'print $1'})"
echo "NEW image: $(du -sh ./image.tar.gz | awk {'print $1'})"

mkdir -p $dirold/imagefs $dirnew/imagefs
tar -zxf $dirold/image.tar.gz -C $dirold/imagefs
tar -zxf ./image.tar.gz -C $dirnew/imagefs

echo "OLD imagefs: $(du -sh $dirold/imagefs | awk {'print $1'})"
echo "NEW imagefs: $(du -sh $dirnew/imagefs | awk {'print $1'})"

echo "======================================================================"
echo "Package count:"
echo "======================================================================"
echo "OLD packages: $(chroot $dirold/imagefs /bin/bash -c "rpm -qa | wc -l")"
echo "NEW packages: $(chroot $dirnew/imagefs /bin/bash -c "rpm -qa | wc -l")"

echo "======================================================================"
echo "Package diff:"
echo "======================================================================"
chroot $dirold/imagefs /bin/bash -c 'rpm -qa --qf "%{NAME}\n" | sort > /tmp/pkglist.out'
chroot $dirnew/imagefs /bin/bash -c 'rpm -qa --qf "%{NAME}\n" | sort > /tmp/pkglist.out'
chroot $dirold/imagefs /bin/bash -c 'rpm -qa | sort > /tmp/pkglist-versions.out'
chroot $dirnew/imagefs /bin/bash -c 'rpm -qa | sort > /tmp/pkglist-versions.out'
diff $dirold/imagefs/tmp/pkglist.out $dirnew/imagefs/tmp/pkglist.out

echo "======================================================================"
echo "Package versions diff:"
echo "======================================================================"
sdiff -s $dirold/imagefs/tmp/pkglist-versions.out $dirnew/imagefs/tmp/pkglist-versions.out

echo "======================================================================"
echo "Kernel version info:"
echo "======================================================================"
echo "OLD KERNEL: $(grep kernel $dirold/imagefs/tmp/pkglist-versions.out | grep -v tools | grep -v libs)"
echo -e "\nNEW KERNEL: $(grep kernel $dirnew/imagefs/tmp/pkglist-versions.out | grep -v tools | grep -v libs)"

rm -rf $dirold $dirnew
