#!/usr/bin/env bash

[[ $VERBOSE == 1 ]] && set -x
set -o nounset -o pipefail -o errexit

centver=$1
arch=$2
outdir=$3

case "$centver" in
'7')
	path="https://cloud.centos.org/centos/7/images"
	file=CentOS-7-$arch-GenericCloud-1801-01.raw.tar.gz
	;;
*) echo 'unknown centos version' && exit 1 ;;
esac

echo "Fetching keys"
gpg --keyserver hkp://ha.pool.sks-keyservers.net --recv-keys \
	C5986B4F1257FFA86632CBA746181433FBB75451

cd "$outdir"
wget -qN "$path/$file" "$path/sha256sum.txt.asc"

# verify signature and also keys used to sign
statusf=$(mktemp -t get-centos-image-keys-XXXXXX)
gpg --quiet --decrypt --status-fd=3 sha256sum.txt.asc >sha256sum.txt 3>"$statusf" 2>/dev/null
grep -q 'VALIDSIG 6341AB2753D78A78A7C27BB124C6A8A7F4A80EB5' "$statusf"
rm -f "$statusf"

grep "$file" sha256sum.txt | sha256sum --status -c

tar -zxf "$file"
rawfile=${file%%.raw*}.raw
mkdir -p /mnt/loop
sectorsize=$(fdisk -l "$rawfile" | sed -n '/^Units:/ s|.*= \([0-9]\+\).*|\1|p')
startsector=$(fdisk -l "$rawfile" | sed -n "/$rawfile/"' s|.*\*\s*\([0-9]\+\).*|\1|p')
offset=$((startsector * sectorsize))
mount -o ro,loop,offset=$offset "$rawfile" /mnt/loop
tar -czf rootfs.tar.gz -C /mnt/loop .
umount /mnt/loop
