#!/usr/bin/env bash

[[ $VERBOSE == 1 ]] && set -x
set -o nounset -o pipefail -o errexit

version=$1
arch=$2
outdir=$3

case $arch in
aarch64) arch=arm64 ;;
x86_64) arch=amd64 ;;
esac

case "$version" in
'14.04') fullversion=$version.5 ;;
'16.04') fullversion=$version.4 ;;
'17.10') fullversion=$version ;;
*) echo "$version is not supported, sorry" && exit 1 ;;
esac

path="http://cdimage.ubuntu.com/ubuntu-base/releases/$version/release"
file=ubuntu-base-$fullversion-base-$arch.tar.gz

echo "Fetching keys"
gpg --keyserver hkp://ha.pool.sks-keyservers.net --recv-keys \
	843938DF228D22F7B3742BC0D94AA3F0EFE21092 \
	C5986B4F1257FFA86632CBA746181433FBB75451

cd "$outdir"
wget -qN "$path/$file" "$path/SHA256SUMS" "$path/SHA256SUMS.gpg"

# verify signature and also keys used to sign
statusf=$(mktemp -t get-ubuntu-image-keys-XXXXXX)
gpg --quiet --verify --status-fd=3 SHA256SUMS.gpg SHA256SUMS 3>"$statusf" 2>/dev/null
grep -q 'VALIDSIG 843938DF228D22F7B3742BC0D94AA3F0EFE21092' "$statusf"
grep -q 'VALIDSIG C5986B4F1257FFA86632CBA746181433FBB75451' "$statusf"
rm -f "$statusf"

grep "$file" SHA256SUMS | sha256sum --status -c
ln -s "$file" rootfs.tar.gz
