#!/usr/bin/env bash

[[ $VERBOSE == 1 ]] && set -x
set -o nounset -o pipefail -o errexit

centver=$1
arch=$2
outdir=$3
mntpoint=/mnt/loop

case "$centver" in
'7')
	path="https://cloud.centos.org/centos/7/images"
	file=CentOS-7-$arch-GenericCloud-1801-01.raw.tar.gz
	;;
*) echo 'unknown centos version' && exit 1 ;;
esac

if mount | grep $mntpoint > /dev/null; then
	echo "Abort! Is $mntpoint already in use?"
	exit 1
else
	echo "Mountpoint $mntpoint is available"
fi

echo "Fetching keys"
wget -4 http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-7 -O ./RPM-GPG-KEY-CentOS-7

echo "Import keys"
gpg --import ./RPM-GPG-KEY-CentOS-7
gpg --quiet --with-fingerprint ./RPM-GPG-KEY-CentOS-7
rm -f ./RPM-GPG-KEY-CentOS-7

echo "Fetching official base"
cd "$outdir"
wget -4 -qN "$path/$file" "$path/sha256sum.txt.asc" "$path/sha256sum.txt"

echo "Verifying sha256..."
grep "$file" sha256sum.txt | sha256sum --status -c
statusf=$(mktemp -t get-centos-image-keys-XXXXXX)
gpg --verify --status-fd=3 ./sha256sum.txt.asc 3>"$statusf"
grep -q "VALIDSIG 6341AB2753D78A78A7C27BB124C6A8A7F4A80EB5" "$statusf"
grep $file sha256sum.txt.asc | sudo tee /proc/self/fd/2 | sha256sum --check - | grep OK
rm -f "$statusf"

echo "Extracting raw archive..."
tar -zxf "$file"
rawfile=${file%%.raw*}.raw
mkdir -p $mntpoint

startsector=$(fdisk -l "$rawfile" | sed -n "/$rawfile/"' s|.*\*\s*\([0-9]\+\).*|\1|p')
sectorsize=$(fdisk -l "$rawfile" | sed -n '/^Units:/ s|.*= \([0-9]\+\).*|\1|p')
offset=$((startsector * sectorsize))

if [ -z "$sectorsize" ]; then
	startsector=$(file $rawfile | sed -n -e 's/.* startsector *\([0-9]*\),.*/\1/p')
	offset=$(expr $startsector '*' 512)
fi


echo "Mounting raw file..."
sudo mount -o ro,loop,offset=$offset "$rawfile" $mntpoint

echo "Making rootfs archive from mount..."
tar -czf rootfs.tar.gz -C $mntpoint .

echo "Cleaning up..."
sudo umount $mntpoint
rm -f $file $rawfile
