#!/bin/bash

#set -o nounset -o pipefail -o errexit

centver=$1
arch=$2
outdir=$3

case "$centver" in
'7')
	path="https://cloud.centos.org/centos/7/images"
	file=CentOS-7-$arch-GenericCloud-1801-01.raw.tar.gz
	;;
esac

cd "$outdir"
wget -qN "$path/$file" "$path/sha256sum.txt" "$path/sha256sum.txt.asc" "https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7"

# verify signature and also keys used to sign
statusf=$(mktemp -t get-centos-image-keys-XXXXXX)
gpg --quiet --import RPM-GPG-KEY-CentOS-7
gpg --quiet --verify --status-fd=3 sha256sum.txt.asc sha256sum.txt 3>"$statusf" 2>/dev/null
grep -q '4288a7c038066d4686b7d829b30b662b8cc76dd3f380db452e6ac4358d6cbd45' "$statusf"
sha256sum -c sha256sum.txt.asc 2>&1 | grep OK
rm -f "$statusf"

grep "$file" sha256sum.txt | sha256sum --status -c
ln -s "$file" centos-image.raw.tar.gz

tar -zxf centos-image.raw.tar.gz
rawfile=$(echo $file | sed 's/.tar.gz//g')
mkdir -p /mnt/loop
startsector=$(file $rawfile | sed -n -e 's/.* startsector *\([0-9]*\),.*/\1/p')
offset=$(expr $startsector '*' 512)

mount -o ro,loop,offset=$offset $rawfile /mnt/loop
tar -czf rootfs.tar.gz -C /mnt/loop .
umount /mnt/loop
