#!/bin/bash

set -o nounset -o pipefail -o errexit

codename=$1
arch=$2
outdir=$3

case "$codename" in
'trusty')
	path="http://cdimage.ubuntu.com/ubuntu-base/releases/14.04.5/release"
	file=ubuntu-base-14.04-core-$arch.tar.gz
	;;
'xenial')
	path="http://cdimage.ubuntu.com/ubuntu-base/releases/$codename/release/"
	file=ubuntu-base-16.04.4-base-$arch.tar.gz
	;;
'zesty')
	path="http://cdimage.ubuntu.com/ubuntu-base/releases/$codename/release"
	file=ubuntu-base-17.04-base-$arch.tar.gz
	;;
'artful')
        path="http://cdimage.ubuntu.com/ubuntu-base/releases/$codename/release"
        file=ubuntu-base-17.10-base-$arch.tar.gz
        ;;
esac

cd "$outdir"
wget -qN "$path/$file" "$path/SHA256SUMS" "$path/SHA256SUMS.gpg"

# verify signature and also keys used to sign
statusf=$(mktemp -t get-ubuntu-image-keys-XXXXXX)
gpg --quiet --verify --status-fd=3 SHA256SUMS.gpg SHA256SUMS 3>"$statusf" 2>/dev/null
grep -q 'VALIDSIG 843938DF228D22F7B3742BC0D94AA3F0EFE21092' "$statusf"
grep -q 'VALIDSIG C5986B4F1257FFA86632CBA746181433FBB75451' "$statusf"
rm -f "$statusf"

grep "$file" SHA256SUMS | sha256sum --status -c
ln -s "$file" rootfs.tar.gz
